[build]
name = "USLCI+"
version = "0.1.0"
# repository = "https://github.com/FLCAC-admin/uslci_plus/"

[dependencies]
USLCI_Database_Public = "1.2026-03.0"
US_electricity_baseline = "*"  # wildcard that resovles to latest release
Woody_biomass = "1.2026-05.1"
# Building_Systems = "1.2025-09.0"
# construction_materials = "1.2025-07.0"
# USEEIO_v2 = "1.2022-06.0"

# (later) <arbitrary_github_repo> = <url>
